& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'$this.Name' = 'TASK_FORM'
'MAIN_TASK_PANNEL.Name' = 'MAIN_TASK_PANNEL'
'Panel1.Name' = 'Panel1'
'MAIN_TASK_LABEL_PANNEL.Name' = 'MAIN_TASK_LABEL_PANNEL'
'MAIN_TASKACTIVECOUNT_LABEL.Name' = 'MAIN_TASKACTIVECOUNT_LABEL'
'MAIN_TASK_LABEL.Name' = 'MAIN_TASK_LABEL'
'MAIN_TASK_VERSION_PANNEL.Name' = 'MAIN_TASK_VERSION_PANNEL'
'MAIN_TASK_ELAPSEDTIME_PANNEL.Name' = 'MAIN_TASK_ELAPSEDTIME_PANNEL'
'MAIN_TASK_ELAPSEDTIMECOUNT_LABEL.Name' = 'MAIN_TASK_ELAPSEDTIMECOUNT_LABEL'
'MAIN_TASK_ELAPSEDTIMETITLE_LABEL.Name' = 'MAIN_TASK_ELAPSEDTIMETITLE_LABEL'
'MAIN_OVERVIEWTASK_PANNEL.Name' = 'MAIN_OVERVIEWTASK_PANNEL'
'ProgressBar1.Name' = 'ProgressBar1'
'MAIN_TOTALPROGRESS_PROGRESSBAR.Name' = 'MAIN_TOTALPROGRESS_PROGRESSBAR'
'MAIN_TASKOVERVIEWLABEL_PANNEL.Name' = 'MAIN_TASKOVERVIEWLABEL_PANNEL'
'Label1.Name' = 'Label1'
'MAIN_OVERVIEW_LABEL.Name' = 'MAIN_OVERVIEW_LABEL'
}
}