& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'$this.Name' = 'CREDSPROMPT_FORM'
'TextBox1.Name' = 'TextBox1'
'TextBox2.Name' = 'TextBox2'
'Button1.Name' = 'Button1'
'Button2.Name' = 'Button2'
'CREDSPROMPT_USERNAME_TEXTBOX.Name' = 'CREDSPROMPT_USERNAME_TEXTBOX'
'CREDSPROMPT_PASSWORD_TEXTBOX.Name' = 'CREDSPROMPT_PASSWORD_TEXTBOX'
'CREDSPROMPT_CONFIRM_BUTTON.Name' = 'CREDSPROMPT_CONFIRM_BUTTON'
'CREDSPROMPT_CANCEL_BUTTON.Name' = 'CREDSPROMPT_CANCEL_BUTTON'
'Label1.Name' = 'Label1'
'CREDSPROMPT_USERNAME_LABEL.Name' = 'CREDSPROMPT_USERNAME_LABEL'
'CREDSPROMPT_PASSWORD_LABEL.Name' = 'CREDSPROMPT_PASSWORD_LABEL'
'CREDSPROMPT_CUSTOMTEXT_LABEL.Name' = 'CREDSPROMPT_CUSTOMTEXT_LABEL'
}
}