& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'REMINDER_MINS_INPUT_TEXTBOX.Name' = 'REMINDER_MINS_INPUT_TEXTBOX'
'Label1.Name' = 'Label1'
'REMINDER_CONFIRM_BUTTON.Name' = 'REMINDER_CONFIRM_BUTTON'
'REMINDER_MINS_DESC_LABEL.Name' = 'REMINDER_MINS_DESC_LABEL'
'REMINDER_DESC_LABEL.Name' = 'REMINDER_DESC_LABEL'
'REMINDER_ESTIMATEDTIME_LABEL.Name' = 'REMINDER_ESTIMATEDTIME_LABEL'
'REMINDER_CANCEL_BUTTON.Name' = 'REMINDER_CANCEL_BUTTON'
'Button1.Name' = 'Button1'
'$this.Name' = 'RESTARTREMINDER_FORM'
}
}