& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'RESTARTOPTIONS_DESC_LABEL.Name' = 'RESTARTOPTIONS_DESC_LABEL'
'RESTARTOPTIONS_RESTARTPC_BUTTON.Name' = 'RESTARTOPTIONS_RESTARTPC_BUTTON'
'RESTARTOPTIONS_RESTARTBIOS_BUTTON.Name' = 'RESTARTOPTIONS_RESTARTBIOS_BUTTON'
'RESTARTOPTIONS_RESTARTRE_BUTTON.Name' = 'RESTARTOPTIONS_RESTARTRE_BUTTON'
'RESTARTOPTIONS_RESTARTFPCA_BUTTON.Name' = 'RESTARTOPTIONS_RESTARTFPCA_BUTTON'
'RESTARTOPTIONS_REMINDLATER_BUTTON.Name' = 'RESTARTOPTIONS_REMINDLATER_BUTTON'
'RESTARTOPTIONS_NORESTART_BUTTON.Name' = 'RESTARTOPTIONS_NORESTART_BUTTON'
'$this.Name' = 'RESTARTOPTIONS_FORM'
}
}