& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'PROGRESS_LABEL.Name' = 'PROGRESS_LABEL'
'PROGRESS_TEXT_LABEL.Name' = 'PROGRESS_TEXT_LABEL'
'UPDATINGTO_NUM_LABEL.Name' = 'UPDATINGTO_NUM_LABEL'
'ProgressBar1.Name' = 'ProgressBar1'
'CURRENTVERSION_TITLE_LABEL.Name' = 'CURRENTVERSION_TITLE_LABEL'
'Label1.Name' = 'Label1'
'INFO_LIVEINFO_LABEL.Name' = 'INFO_LIVEINFO_LABEL'
'MAIN_UPDATER_PANEL.Name' = 'MAIN_UPDATER_PANEL'
'CURRENTVERSION_NUM_LABEL.Name' = 'CURRENTVERSION_NUM_LABEL'
'RichTextBox1.Name' = 'RichTextBox1'
'UPDATINGTO_LABEL.Name' = 'UPDATINGTO_LABEL'
'UPDATINGTO_TITLE_LABEL.Name' = 'UPDATINGTO_TITLE_LABEL'
'LIVESTATUS_TEXT_LABEL.Name' = 'LIVESTATUS_TEXT_LABEL'
'MAIN_UPDATE_PROGRESSBAR.Name' = 'MAIN_UPDATE_PROGRESSBAR'
'$this.Name' = 'UPDATER_MAIN_FORM'
'LIVEINFO_TEXTBOX.Name' = 'LIVEINFO_TEXTBOX'
'PROGRESS_NUM_LABEL.Name' = 'PROGRESS_NUM_LABEL'
}
}